export const actionTypes = {
  PRODUCTS_FETCHING: "PRODUCTS_FETCHING",
  PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
  PRODUCTS_ERROR: "PRODUCTS_ERROR",
  ADD_TO_CART: "ADD_TO_CART",
  CHANGE_QUANTITY: "CHANGE_QUANTITY",
  REMOVE_ITEM: "REMOVE_ITEM",
};
