export const actionTypes = {
  ADD_TO_CART_FETCHING: "ADD_TO_CART_FETCHING",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",
  REMOVE_TO_CART_FETCHING: "REMOVE_TO_CART_FETCHING",
  REMOVE_TO_CART_SUCCESS: "REMOVE_TO_CART_SUCCESS",
  REMOVE_TO_CART_ERROR: "REMOVE_TO_CART_ERROR"
};
