export const actionTypes = {
  FIRST_NAME: "FIRST_NAME",
  LAST_NAME: "LAST_NAME",
  PHONE_NUMBER: "PHONE_NUMBER",
  EMAIL: "EMAIL",
  ADDRESS: "ADDRESS",
  COUNTRY: "COUNTRY",
  CITY: "CITY",
  ZIPCODE: "ZIPCODE",
  INSTRUCTIONS: "INSTRUCTIONS",
};
