export const actionTypes = {
    DOWN_VOTE: "DOWN_VOTE",
    UP_VOTE: "UP_VOTE",
    SET_FAVORITE: "SET_FAVORITE",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE: "REMOVE",
    CHANGE: "CHANGE",
    IS_LOADING: "IS_LOADING",
    HAS_ERROR: "HAS_ERROR",
    LOADING_ERROR: "LOADING_ERROR",
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_CART_ITEMS: "SET_CART_ITEMS",
    FETCH_PRDUCTS: "FETCH_PRODUCTS"
  };
  