export const actionTypes = {
  PRODUCTS_FETCHING: "PRODUCTS_FETCHING",
  PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
  PRODUCTS_ERROR: "PRODUCTS_ERROR",
  DOWN_VOTE: "DOWN_VOTE",
  UP_VOTE: "UP_VOTE",
  SET_FAVORITE: "SET_FAVORITE",
  SAVE_NEW_PRODUCT: "SAVE_NEW_PRODUCT"
}