export const actionTypes = {
  ADD_PRODUCT_FETCHING: "ADD_PRODUCT_FETCHING",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_ERROR: "ADD_PRODUCT_ERROR",
  PRODUCTS_FETCHING: "PRODUCTS_FETCHING",
  PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
  PRODUCTS_ERROR: "PRODUCTS_ERROR",
  ADD_TO_CART: "ADD_TO_CART",
  CHANGE: "CHANGE",
  REMOVE: "REMOVE",
  DOWN_VOTE: "DOWN_VOTE",
  UP_VOTE: "UP_VOTE",
  SET_FAVORITE: "SET_FAVORITE",
  SAVE_NEW_PRODUCT: "SAVE_NEW_PRODUCT"
}